name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
      with:
        flutter-version: '3.35.4'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test
